command: ["uv", "run", "custom-mcp-server"]
env:
  # DATABRICKS_HOST is automatically set by Databricks Apps runtime
  # Configure the agent endpoint name and description below
  - name: AGENT_ENDPOINT_NAME
    value: my-agent-endpoint
  - name: AGENT_DESCRIPTION
    value: Ask questions to the AI agent